POST http://localhost:3003/api/notes 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImgwbG1lcyIsImlkIjoiNjNjMTNiOGNhMGEzZGEzYjc3YjFiYjdlIiwiaWF0IjoxNjczNjEyNjEyfQ.26_Vxh-sy4E1v8D8Vrd4eZooeL0Ynx9uSkunsJdLTGc

{
  "userId": "63c13b8ca0a3da3b77b1bb7e",
  "content": "I'm still authorized!",
  "important": false 
}