POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvbWVyIiwiaWQiOiI2M2M5NmYzODgzOTRhNzhlNjQ0N2E3NTQiLCJpYXQiOjE2NzQxNjAzOTYsImV4cCI6MTY3NDE2Mzk5Nn0.0INte5eRheA0NXnQ980PF-W4Bc9Zzk0QoUWBBchaiZw

{
  "title": "Test 3",
  "author": "Test 3",
  "url": "https://test2.io/",
  "likes": 1,
  "userId": "63c96f388394a78e6447a754"
}